#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import csv
import matplotlib.pyplot as plt
import numpy as np
import sys

if len(sys.argv) != 2:
    print('Please use the file generated by the tsp as first argument')

filename = sys.argv[1]
best_tours = []
with open(filename,'r') as csvfile:
    data = csv.reader(csvfile, delimiter=',', quoting=csv.QUOTE_NONNUMERIC)
    for i,row in enumerate(data):
        plt.plot(range(1, len(row)), row[:len(row) - 1])
        best_tours.append(row[len(row) - 2])

# graph plot
plt.xlabel('Iteration')
plt.ylabel('Tour Length')
plt.savefig('genetic_tsp_curves.png')
plt.close()

# boxplot
plt.boxplot(best_tours)
plt.xlabel('Tour Length')
plt.savefig('genetic_tsp_boxplot.png')
plt.close()

# pie chart
sizes = {}
for best_tour in best_tours:
    if best_tour in sizes:
        sizes[best_tour] += 1
    else:
        sizes[best_tour] = 1

labels = sizes.keys()
values = sizes.values()
plt.pie(values, labels=labels, autopct='%1.0f%%', pctdistance=1.1, labeldistance=1.3)
plt.axis('equal')
plt.savefig('genetic_tsp_piechart.png')
